/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.*;

public class MySQLExample {
    public static void main(String[] args) {
        // 1. 添加 MySQL 连接驱动程序依赖
        // 例如使用 Maven 添加以下依赖:
        // <dependency>
        //     <groupId>mysql</groupId>
        //     <artifactId>mysql-connector-java</artifactId>
        //     <version>8.0.28</version>
        // </dependency>

        // 2. 建立数据库连接
        String url = "jdbc:mysql://172.31.21.153:32639,172.31.32.194:32639,172.31.47.15:32639/mysql?useSSL=false";
        String username = "root";
        String password = "77zkv2w8";

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to database!");

            // 3. 执行 SQL 查询
            String query = "SELECT * FROM user";
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(query)) {

                // 4. 处理查询结果
                while (resultSet.next()) {
		    String host = resultSet.getString("Host");
                    String user = resultSet.getString("User");
                    System.out.println("Host: " + host + ", User: " + user);
                }
            }

	    connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

