/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.*;

public class PostgreSQLExample {
    public static void main(String[] args) {
        // 1. 建立数据库连接
        String url = "jdbc:postgresql://172.31.21.153:30150,172.31.32.194:30150,172.31.47.15:30150/postgres?useSSL=false";
        String username = "postgres";
        String password = "fx9xflfb";

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to database!");

            // 2. 执行 SQL 查询
            String query = "SELECT * FROM pg_stat_activity";
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(query)) {

                // 3. 处理查询结果
                while (resultSet.next()) {
		    String pid = resultSet.getString("Pid");
                    String usename = resultSet.getString("usename");
                    System.out.println("Pid: " + pid + ", Usename: " + usename);
                }
            }

	    connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

